Web_Projects/LetsChat/config/routes.rb
Rails.application.routes.draw do

  root 'tweets#index'

  resources :tweets do 
  	resources :comments
  end
  
  resources :users do
  	resources :follows
    resources :messages
  end

  get "/signup" => 'users#new'
  get "/login" => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  

end

Web_Projects/LetsChat/app/models/tweet.rb
class Tweet < ActiveRecord::Base

	validates_presence_of :content

	has_many :comments, class_name: 'Comment', foreign_key: 'tweet_id'

	has_many :like

	has_many :liker, class_name: 'User', :through => :like

end

Web_Projects/LetsChat/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	before_action :find_user
	def find_user
		if (!session["user_id"].present?)
			redirect_to login_path
		end
	end

	before_action :authorize, only: [:edit, :destroy, :update]
	def authorize
		@tweet = Tweet.find_by(id: params["id"])
		@user = User.find_by(id: @tweet.user_id)
		if @user.blank? || session[:user_id] != @user.id
			redirect_to root_url, notice: "You need login!"
		end
	end
	
	def index
		if params[:keyword].present?
			
			if User.where("username LIKE ?", "%#{params[:keyword]}").present?
				userid = User.find_by(username: params[:keyword].downcase).id
				@tweets = Tweet.where("user_id LIKE ?", "%#{userid}")

			else
				redirect_to root_url, notice: "Search ID doesn't exist!"
				return
			end
			@tweets = @tweets.order('date desc').paginate(:per_page => 5, :page => params[:page])
			return
		end
		
		if params["user_id"].present?
			@tweets = Tweet.where(user_id: params["user_id"])
		else
			@tweets = Tweet.all
		end
		@tweets = @tweets.order('date desc').paginate(:per_page => 5, :page => params[:page])
	end

	def show
		@tweet = Tweet.find_by(id: params["id"])
	end

	def create
		tweet = Tweet.new
		tweet.content = params[:post_tweet]
		tweet.date = DateTime.now.to_i
		tweet.user_id = session["user_id"]
		tweet.save
		redirect_to root_path
	end

	def destroy
		@tweet.delete
		redirect_to root_path
	end

	def edit
		@tweet = Tweet.find_by(id: params["id"])
	end

	def update
		@tweet.content = params["update_tweet"]
		@tweet.image = params["image"]
		@tweet.date = DateTime.now.to_i
		@tweet.save
		redirect_to root_path
	end

end

Web_Projects/LetsChat/app/views/tweets/edit.html.erb
<div class="col-xs-9">
	<%= form_tag tweet_path(@tweet.id), method:"patch" do %>
	<label for="update_tweet">Update the tweet</label>
	<br>
	<textarea name="update_tweet" class="post-tweet" rows="5">
		<%= @tweet.content%>
	</textarea>
	<label for="image">Image</label>
	<br>
	<input name="image" size="80" value="<%= @tweet.image%>">
	<p>
		<br>
		<button class="btn btn-success">UPDATE</button>
	</p>
	<% end %>
</div>

Web_Projects/LetsChat/app/views/tweets/index.html.erb
<div class="row">
  <div class="col-xs-1" id="new_link">

  </div>

  <!-- middle part -->
  <div class="col-xs-8">
    <div class="jumbotron">
      <%= form_tag tweets_path, method:"post" do %>
      <label for="post_tweet">What news do you want to share with others?</label>
      <br>
      <textarea name="post_tweet" class="post-tweet" rows="5"></textarea>
      <button class="btn btn-success">POST</button>
      <% end %>
    </div>
    <!---list tweets -->
    <% @tweets.each do |tweet| %>
    <div class="jumbotron">
      <div class="row">
        <div class="col-xs-2">
          <%= image_tag(User.find_by(id: tweet.user_id).image, class: "protrait")%>
        </div>
        <div class="col-xs-8">
          <h4>          
            <%= link_to User.find_by(id: tweet.user_id).username, tweets_path(:user_id => tweet.user_id) %>
            <br>
            <small ><%= link_to "follow", user_follows_path(:user_id => session["user_id"], :fan => session["user_id"], :star => tweet.user_id), method: "post" %>

              <% if Follow.find_by(fan_id: session["user_id"], star_id: tweet.user_id).present? %>
              <%= link_to "/ unfollow", user_follow_path(:user_id => session["user_id"], :id => Follow.find_by(fan_id: session["user_id"], star_id: tweet.user_id).id), method: "delete"%>
              <% end %>

            </small>
          </h4>
          <br>
          <%= tweet.content %>
          <br>
          <% if tweet.image.present? %>
          <%= image_tag tweet.image, class: "tweet-image" %>
          <% end %>
          <br><br>
          <small><%= Time.at(tweet.date).strftime("Posted on %m/%d/%y at %I:%M%p") %></small>
        </div>
        <% if tweet.user_id == session["user_id"].to_i %>
        <div class="col-xs-1">
          <%= link_to 'Edit', edit_tweet_path(tweet.id) %>
        </div>
        <div class="col-xs-1">
          <%= link_to 'Delete', tweet_path(tweet.id), method: :delete %>
        </div>
        <% end %>
      </div>
      <hr>
      <div class="col-xs-3">
        <a href="#" >Like</a>
      </div>
      <div class="col-xs-3">
        <%= link_to 'Comment', new_tweet_comment_path(tweet.id), remote: true%>
      </div>
      <div class="col-xs-3">
        <%= link_to 'View it', tweet_path(tweet.id)%>
      </div>
      <div class="col-xs-3">
        Share
      </div>
      <br>

      <!-- hidden part for comments -->
      <div class="comment-list-<%= tweet.id %>" style="display:none;margin-top:20px">
        <div id="comment_of_<%= tweet.id %>"></div>
        <% comments = Comment.where(tweet_id: tweet.id).order('date desc') %>
        <% comments.each do |comment| %>
        <div class="row" id="comment-<%=comment.id%>">
          <hr class="dividing_line">
          <div class="col-xs-1">
            <%= image_tag(User.find_by(id: comment.user_id).image, class: "protrait")%>
          </div>
          <div class="col-xs-10">
            <h4>
              <%= User.find_by(id: comment.user_id).username %>
              <div class="pull-right">
                <small><%= Time.at(comment.date).strftime("Commented on %m/%d/%y at %I:%M%p") %></small>
              </div>
            </h4>
            <br>
            <%= comment.content %>
            <br>
          </div>
          <% if comment.user_id == session["user_id"].to_i %>
          <div class="col-xs-1">
            <%= link_to 'Delete', tweet_comment_path(tweet.id ,comment.id), 
            method: :delete, 
            remote: true, 
            data: { confirm: "Are you sure to delete it?" } 
            %>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>


    </div>
    <% end %>
  </div>

  <!-- right nav bar -->
  <div class="col-xs-3">
    <div class="jumbotron" style="position: fixed">
      <%= image_tag(session["user_image"], class: "protrait")%>
      <br>
      <%= session["username"]%>
      <hr>
      <div class="row">
        <div class="col-xs-6">
          <%= link_to "following", user_follows_path(session["user_id"]) %>
          <%= link_to "follower", user_follows_path(session["user_id"]) %>
          <%= link_to "tweets", tweets_path(:user_id => session["user_id"]) %>
        </div>
        <div class="col-xs-2">
          <%= Follow.where(fan_id: session["user_id"]).count%><br>
          <%= Follow.where(star_id: session["user_id"]).count%><br>
          <%= Tweet.where(user_id: session["user_id"]).count%><br>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="text-center">
  <%= will_paginate @tweets, :renderer => BootstrapPagination::Rails %>
</div>

<script>
  $(function(){

    $('.tweet-image').click(function () {
      if($(this).outerWidth() < $(this).parent().outerWidth()){
        $(this).css("width", $(this).parent().outerWidth());
      }
      else {
        $(this).css("width", $(this).parent().outerWidth()*0.3);
      }
    });

  });
</script>

Web_Projects/LetsChat/app/views/tweets/show.html.erb
  <div class="col-xs-8">
  	<div class="jumbotron">
  		<div class="row">
  			<div class="col-xs-2">
  				<%= image_tag(User.find_by(id: @tweet.user_id).image, class: "protrait")%>
  			</div>
  			<div class="col-xs-8">
  				<h4><%= User.find_by(id: @tweet.user_id).username %></h4>
  				<br>
  				<%= @tweet.content %>
  				<br>
  				<% if @tweet.image.present? %>
  				<%= image_tag @tweet.image, class: "tweet-image" %>
  				<% end %>
  				<br><br>
  				<small><%= Time.at(@tweet.date).strftime("Posted on %m/%d/%y at %I:%M%p") %></small>
  			</div>
  			<% if @tweet.user_id == session["user_id"].to_i %>
  			<div class="col-xs-1">
  				<%= link_to 'Edit', edit_tweet_path(@tweet.id) %>
  			</div>
  			<div class="col-xs-1">
  				<%= link_to 'Delete', tweet_path(@tweet.id), method: :delete %>
  			</div>
  			<% end %>
  		</div>
  		<hr>
  		<div class="col-xs-3">
  			<a href="#" >Like</a>
  		</div>
  		<div class="col-xs-3">
  			Share
  		</div>
  		<br>

  		<!-- hidden part for comments -->
  		<div style="margin-top:20px">
  			<%= form_tag tweet_comments_path(@tweet.id), method:"post" do %>
  			<label for="comment">
  				<%= image_tag(session["user_image"], class: "protrait")%>
  				<%= session["username"] %>
  			</label>
  			<br><br>
  			<input name="comment" style="width:80%">
  			<button class="btn btn-success">Comment</button>
  			<% end %>
  			<% comments = Comment.where(tweet_id: @tweet.id).order('date desc') %>
  			<% if ! comments.nil? %>
  			<% comments.each do |comment| %>
  			<hr class="dividing_line">
  			<div class="row">
  				<div class="col-xs-1">
  					<%= image_tag(User.find_by(id: comment.user_id).image, class: "protrait")%>
  				</div>
  				<div class="col-xs-10">
  					<h4>
  						<%= User.find_by(id: comment.user_id).username %>
  						<div class="pull-right">
              <br><br>
  							<small><%= Time.at(comment.date).strftime("Commented on %m/%d/%y at %I:%M%p") %></small>
  						</div>
  					</h4>
  					<br>
  					<%= comment.content %>
  				</div>
  				<div class="col-xs-1">
  					<% if comment.user_id == session["user_id"].to_i %>
  					<%= link_to 'Delete', tweet_comment_path(@tweet.id ,comment.id), method: :delete%>
  					<% end %>
  				</div>
  			</div>
  			<% end %>
  			<% end %>
  		</div>
  	</div>
  </div>

  <div class="col-xs-3">
  	<% if session["user_id"].present? %>
  	<div class="jumbotron">
  		<%= image_tag(session["user_image"], class: "protrait") %>
  		<%= session["username"]%>
  		<hr>
  		<li>following</li>
  		<li>follower</li>
  		<li>tweets</li>
  	</div>
  	<% end %>
  </div>