Web_Projects/LetsChat/config/routes.rb
Rails.application.routes.draw do

  root 'tweets#index'

  resources :tweets do 
  	resources :comments
  end
  
  resources :users do
  	resources :follows
    resources :messages
  end

  get "/signup" => 'users#new'
  get "/login" => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  

end

Web_Projects/LetsChat/app/models/message.rb
class Message < ActiveRecord::Base

	 validates_presence_of :content
	 
end

Web_Projects/LetsChat/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	before_action :find_user
	def find_user
		if (!session["user_id"].present?)
			redirect_to login_path
		end
	end


	before_action :find_message, only: [:edit, :destroy, :update]
	def find_message
		if !Message.find_by_id(params["id"]).present?
			redirect_to user_messages_path, notice:"The message is not existing!"
		end
	end


	before_action :authorize, only: [:edit, :destroy, :update]
	def authorize
		@message = Message.find_by(id: params["id"])
		@user = User.find_by_id(session["user_id"])
		if @user.blank? || session[:user_id] != @user.id
			redirect_to root_url, notice: "You need login!"
		end
	end

	def index
		@user = User.find_by_id(session["user_id"])
		if params["user_id"].present?
			@messages = Message.where(sender_id: params["user_id"])
			@messages_in = Message.where(receiver_id: session["user_id"])
		end
		@messages = @messages.order('date desc').paginate(:per_page => 5, :page => params[:page])
		@messages_in = @messages_in.order('date desc').paginate(:per_page => 5, :page => params[:page])
	end

	def new
		
	end

	def create
		message = Message.new
		if User.find_by_username(params[:receiver]).present?
			message.receiver_id = User.find_by_username(params[:receiver]).id
			message.content = params[:message]
			message.date = DateTime.now.to_i
			message.sender_id = session["user_id"]
			message.is_read = false
			message.save
			redirect_to user_messages_path
		else
			redirect_to user_messages_path, notice: "No such user existing!"
		end
		
	end

	def update
		# @message.content = params["update_tweet"]
		@message.date = DateTime.now.to_i
		@message.is_read = true
		@message.save
		redirect_to user_messages_path
	end

	def destroy
		@message.delete
		redirect_to user_messages_path
	end

end

Web_Projects/LetsChat/app/views/messages/index.html.erb
<div class="row">
  <div class="col-xs-1" id="new_link">

  </div>
  <div class="col-xs-8">
    <div class="jumbotron">
      <%= form_tag user_messages_path, method:"post" do %>
      <label for="sending message">Compose message?</label>
      <br>
      <textarea name="receiver" rows="1" cols="25" placeholder="Receiver Name"></textarea>
      <br>
      <!-- <textarea name="title" rows="1" cols="50" placeholder="Message Title"></textarea> -->
      <br>
      <textarea name="message" class="create message" rows="5" cols="60" placeholder="Message Body"></textarea>
      <br>
      <button class="btn btn-success">Send</button>
      <% end %>
    </div>

    Messages Sent From <%= @user.username %><br>
    <% if !@messages.present? %>
    <big>YOU HAVE NOT SENT ANY MESSAGES!</big>
    <% end %>
    
    <br>
    <big>YOU HAVE SENT <%= @messages.count %> MESSAGES:</big>

    <!---list messages for sent messages-->
    <% @messages.each do |msg| %>
    <div class="jumbotron">
      <div class="row">
        <div class="col-xs-2">

          <big>To: &nbsp</big>
          <% if User.find_by_id(msg.receiver_id).image.present? %>
          <%= image_tag(User.find_by_id(msg.receiver_id).image, class: "protrait")%>
          <% end %>
        </div>
        <div class="col-xs-8">
          <h4>           
            <%= link_to User.find_by_id(msg.receiver_id).username, tweets_path(user_id: msg.receiver_id) %>
          </h4>
          <% if msg.is_read == false %>
          <small style="color:red">(<%= User.find_by_id(msg.receiver_id).username %> hasn't read this message.)</small>
          <% else %>
          <small style="color:red">(<%= User.find_by_id(msg.receiver_id).username %> has already read this message.)</small>
          <% end %>
          <br>
          <%= msg.content %>
          <br>
          <small><%= Time.at(msg.date) %></small>
        </div>
        <div class="col-xs-1">
          <%= link_to 'Delete', user_message_path(session["user_id"], msg.id), method: :delete %>
          <!-- <#%= link_to 'Read', user_message_path(session["user_id"], msg.id), method: :patch %> -->
        </div>
        
      </div>
    </div>
    <% end %>

    <!---list messages for incoming messages-->
    <div><br><br>
      Message Received By <%= @user.username %><br>
      <% if !@messages_in.present? %>
      <big> YOU HAVE NO MESSAGES AVAILABLE TO VIEW! </big>
      <% end %>
      <br>
      <big>YOU HAVE RECEIVED <%= @messages_in.count %> MESSAGES:</big>
      <% @messages_in.each do |msg| %>
      <div class="jumbotron">
        <div class="row">
          <div class="col-xs-2">
            <big>From: &nbsp</big>
            <% if User.find_by_id(msg.sender_id).image.present? %>
            <%= image_tag(User.find_by_id(msg.sender_id).image, class: "protrait")%>
            <% end %>
          </div>
          <div class="col-xs-8">
            <h4>          
              <%= link_to User.find_by_id(msg.sender_id).username, tweets_path(user_id: msg.receiver_id) %>
            </h4>
            <% if msg.is_read == false %>
            <small style="color:red">(This is an un-read message.)</small>
            <% else %>
            <small style="color:red">(You have already read this message.)</small>
            <% end %>
            <br>
            <%= msg.content %>
            <br>
            <small><%= Time.at(msg.date) %></small>
          </div>
          <div class="col-xs-1">
            <%= link_to 'Delete', user_message_path(session["user_id"], msg.id), method: :delete %>
            <%= link_to 'Read', user_message_path(session["user_id"], msg.id), method: :patch %>
          </div>
          
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>