Web_Projects/LetsChat/config/routes.rb
Rails.application.routes.draw do

  root 'tweets#index'

  resources :tweets do 
  	resources :comments
  end
  
  resources :users do
  	resources :follows
    resources :messages
  end

  get "/signup" => 'users#new'
  get "/login" => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  

end

Web_Projects/LetsChat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<style tyep="text/css">

.transbox {
  opacity: 0.80;
  filter: alpha(opacity=80);
  font-size: 18px;
  font-weight: bold;
}
</style>
  <title>Social Networking App</title>
  <%= favicon_link_tag 'chat_icon',type: 'image/png'%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">
            <big style="color:orange;margin-left:0px;">LETsCHAT</big>
            <sub><small>-- Hao Zhou</small></sub>
          </a>
        </div>
        <ul class="nav navbar-nav" style="margin-left:25px">
          <li><a href="/">Home</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Settings
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <% if !session["user_id"].present? %>
              <li><a href="">Account Settings</a></li>
              <% else %>
              <li><%= link_to "Account Settings", user_path(session["user_id"]) %></li>
              <% end %>
              <% if !session["user_id"].present? %>
              <li><a href="">Account Safety</a></li>
              <% else %>
              <li><%= link_to "Account Safety", edit_user_path(session["user_id"])  %></li>
              <% end %>
              <% if !session["user_id"].present? %>
              <li><a href="">Message Center</a></li>
              <% else %>
              <li><%= link_to "Message Center", user_messages_path(session["user_id"]) %></li>
              <% end %>
            </ul>
          </li>
          <% if session["user_id"] == nil %>
          <li><a href="">Messages</a></li>
          <% else %>
          <li><%= link_to "Messages", user_messages_path(session["user_id"]) %></li>
          <% end %>
          <li class="navbar-form">
            <%= form_tag tweets_url, :method => "get" do %>
            <%= text_field_tag :keyword.downcase %>
            <%= submit_tag "Search" %>
            <% end %>
          </li>
          
<!--           <li><a href="">About</a></li>
  <li><a href="">Contact us</a></li> -->
</ul>

<ul class="nav navbar-nav pull-right">
  <% if session["user_id"].present? && User.find_by(id: session["user_id"]).present? %>
  <li><%= link_to User.find_by(id: session["user_id"]).username, user_path(session["user_id"]) %></li>
  <li><%= link_to "Sign Out", logout_path %></li>
  <% else %>
  <li><%= link_to "Sign Up", '/signup' %></li>
  <li><%= link_to "Sign In", '/login' %></li>
  <% end %>
</ul>

</div>
</nav>
</div>
</nav>
</body>


<div class="container" style="padding-top:60px">
  <div class="transbox">
   <% if notice.present? %>
    <div class="alert alert-info" style="text-align: center; width: 70%; margin-left: 10%">
     <%= notice %>
    </div>
   <% end %>
   <%= yield %>
  </div>
</div>

</body>
</html>
<script>
   $.backstretch(
    [ "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-1.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-2.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-3.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/background-4.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-5.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-6.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-7.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-8.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-9.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-10.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-11.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-12.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-13.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-14.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-15.jpg?raw=true"
    , "https://github.com/haouc/Personal_Projects/blob/master/assets/images/Background-16.jpg?raw=true"], {duration: 30000, fade: 750});
</script>